import React from "react";
import { FaBeer, FaBars } from "react-icons/fa";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-dark min-h-screen text-white">
        <div className="flex items-center justify-between px-8 py-4">
          <h1 className="text-4xl">Beebu Imprint</h1>
          <ul className="hidden md:flex md:gap-12">
            <li className="cursor-pointer">Home</li>
            <li className="cursor-pointer">About</li>
            <li className="cursor-pointer">Services</li>
            <li className="cursor-pointer">Contact</li>
          </ul>
          <a
            href="#"
            class="bg-beebu hover:bg-amber-400 text-black text-center py-2 px-4 rounded text-lg hidden md:block"
          >
            Book Session
          </a>
          <FaBars size="32px" className="md:hidden" />
        </div>

        <article className="bg-[url('/bg.png')] bg-center bg-cover bg-no-repeat py-8">
          <div className="my-14 text-center w-[90%] md:w-3/5 mx-auto">
            <h1 className=" text-4xl md:text-6xl ">
              Beebu&rsquo;s Imprint the Best plug for all your
              <span className="text-beebu"> printing </span>needs
            </h1>
            <p className="my-4 text-sm md:text-lg">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit ut
              aliquam, purus sit amet luctus venenatis, lectus magna fringilla
              urna, porttitor rhoncus dolor purus non enim praesent elementum
              facilisis leo, vel fringilla est ullamcorper eget nulla facilisi
              etiam dignissim diam quis enim lobortis scelerisque fermentum dui
              faucibus in ornare quam viverra
            </p>
            <a
              href="#"
              class="bg-beebu hover:bg-amber-400 text-black text-center py-2 px-4 rounded text-lg"
            >
              Book Session
            </a>
          </div>
        </article>
      </section>
    </div>
  );
}
