import React, { useState } from "react";
import { FaBars, FaTimes } from "react-icons/fa";
import { RiMoonClearFill, RiSunFill } from "react-icons/ri";
import Head from "next/head";

export default function Home() {
  const [colorScheme, setcolorScheme] = useState(true);
  const [nav, setnav] = useState(true);

  const handleColorScheme = () => {
    setcolorScheme(!colorScheme);
  };
  const handleNavigation = () => {
    setnav(!nav);
  };
  return (
    <div>
      <Head>
        <title>Beebu Imprint</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section
        className={
          colorScheme
            ? "bg-[#05082B] min-h-screen text-white"
            : "bg-[#EEEEEE] min-h-screen text-black"
        }
      >
        <div className="flex items-center justify-between px-8 py-4">
          <h1 className="text-4xl">Beebu Imprint</h1>
          <ul className="hidden md:flex md:gap-12">
            <li className="cursor-pointer">Home</li>
            <li className="cursor-pointer">About</li>
            <li className="cursor-pointer">Services</li>
            <li className="cursor-pointer">Contact</li>
          </ul>
          <div className="flex items-center gap-4">
            <a
              href="#"
              className={
                colorScheme
                  ? "bg-beebu hidden md:block  hover:bg-amber-400 text-black text-center py-2 px-4 rounded text-lg"
                  : "bg-black hidden md:block hover:bg-gray-700 text-white text-center py-2 px-4 rounded text-lg"
              }
            >
              Book Session
            </a>
            {nav ? (
              <FaBars
                size="32px"
                className="md:hidden"
                onClick={handleNavigation}
              />
            ) : (
              <FaTimes
                size="32px"
                className="md:hidden"
                onClick={handleNavigation}
              />
            )}
            <button>
              {colorScheme ? (
                <RiMoonClearFill
                  size="32px"
                  className="beebu cursor-pointer"
                  onClick={handleColorScheme}
                />
              ) : (
                <RiSunFill
                  size="32px"
                  className="beebu cursor-pointer"
                  onClick={handleColorScheme}
                />
              )}
            </button>
          </div>
        </div>

        {nav ? (
          <div>
            <article
              className={
                colorScheme
                  ? "bg-[url('/bg.png')] bg-center bg-cover bg-no-repeat py-8"
                  : "bg-[url('/bgGG.png')] bg-center bg-cover bg-no-repeat py-8"
              }
            >
              <div className="my-14 text-center w-[90%] md:w-3/5 mx-auto">
                <h1 className=" text-4xl md:text-6xl ">
                  Beebu&rsquo;s Imprint the Best plug for all your
                  <span className={colorScheme ? "text-beebu" : "text-black"}>
                    {" "}
                    printing{" "}
                  </span>
                  needs
                </h1>
                <p className="my-4 text-sm md:text-lg">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit ut
                  aliquam, purus sit amet luctus venenatis, lectus magna
                  fringilla urna, porttitor rhoncus dolor purus non enim
                  praesent elementum facilisis leo, vel fringilla est
                  ullamcorper eget nulla facilisi etiam dignissim diam quis enim
                  lobortis scelerisque fermentum dui faucibus in ornare quam
                  viverra
                </p>
                <a
                  href="#"
                  className={
                    colorScheme
                      ? "bg-beebu hover:bg-amber-400 text-black text-center py-2 px-4 rounded text-lg"
                      : "bg-black hover:bg-gray-700 text-white text-center py-2 px-4 rounded text-lg"
                  }
                >
                  Book Session
                </a>
              </div>
            </article>
          </div>
        ) : (
          <div className="py-12">
            <ul className="flex flex-col items-center gap-16">
              <li className="cursor-pointer text-xl">Home</li>
              <li className="cursor-pointer text-xl">About</li>
              <li className="cursor-pointer text-xl">Services</li>
              <li className="cursor-pointer text-xl">Contact</li>
              <a
                href="#"
                className={
                  colorScheme
                    ? "bg-beebu hover:bg-amber-400 text-black text-center py-2 px-4 rounded text-lg"
                    : "bg-black hover:bg-gray-700 text-white text-center py-2 px-4 rounded text-lg"
                }
              >
                Book Session
              </a>
            </ul>
          </div>
        )}
      </section>
    </div>
  );
}
